<a href="https://colab.research.google.com/github/sameer203/Tensorflow_/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor introduction

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# Create tensors with tf.constants()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10, 7],
                     [7,10]])

In [7]:
matrix.ndim

2

In [8]:
matrix_1 = tf.constant([[10., 7.],
                        [3.,2.],
                        [8.,10.]], dtype=tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8., 10.]], dtype=float16)>

In [9]:
matrix_1.ndim

2

In [10]:
#Create a tensor
tensor = tf.constant([[[1,2, 3,],
                       [4,5,6,]],
                       [[7,8, 9,],
                      [10, 11, 12]],
                      [[13, 14,15],
                      [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Creating using tensors using `tf.variable`

In [12]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [13]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating Random Tensors

In [14]:
random_1 = tf.random.Generator.from_seed(42)
random_1= random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [15]:
random_2 =tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [16]:
random_1, random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order ofelements in a tensor

In [17]:
not_shuffled = tf.constant([[10, 7],
                             [3,2],
                            [8,10]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 8, 10]], dtype=int32)>

In [18]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 8, 10]], dtype=int32)>

### Other ways to make tensors

In [19]:
tf.ones([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
tf.zeros(shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Numpy arrays to Tensors

In [21]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting Information from Tensors

In [23]:
rank_4_tensors = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
print("Datatype of every element:", rank_4_tensors.dtype)
print("Number of Dimensions(rank):", rank_4_tensors.ndim)
print("shape of tensor:", rank_4_tensors.shape)
print("Elements along the 0 axis:", rank_4_tensors.shape[0])
print("Elements along the last axis:", rank_4_tensors.shape[-1])
print("the total number of elements in tensor:", tf.size(rank_4_tensors).numpy())

Datatype of every element: <dtype: 'float32'>
Number of Dimensions(rank): 4
shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
the total number of elements in tensor: 120


### Indexing Tensors

In [26]:
# Get the first 2 elements of each tensors
rank_4_tensors[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the 1st element from from each dimension from each index except for the final one
rank_4_tensors[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
# Create the rank2 tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3,7]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [32]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 7]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 7]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  7]]], dtype=int32)>

### Manipulating Tensors

In [37]:
# addition operator
tensor = tf.constant([[10, 7],[3,5]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 15]], dtype=int32)>

In [38]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  50]], dtype=int32)>

In [39]:
#subtraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -5]], dtype=int32)>

In [40]:
#using builtin function
tf.multiply(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60, 100]], dtype=int32)>

### Matrix multiplication 

In [43]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 105],
       [ 45,  46]], dtype=int32)>

In [44]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 105],
       [ 45,  46]], dtype=int32)>

In [51]:
x = tf.constant([[1, 2],
                        [3,4],
                        [5,6]])

y = tf.constant([[7,8,9],
                 [10,11,12],
                 [13,14, 15]])

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]], dtype=int32)>)

In [47]:
tf.matmul(y,x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136],
       [130, 172]], dtype=int32)>

In [58]:
z = tf.constant([[7,8],
                 [10,19],
                 [13, 89]])

In [57]:
a = tf.constant([[7,8,9],
                 [10,11,12],
                 [13,14, 15]])

In [59]:
a,z

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [10, 19],
        [13, 89]], dtype=int32)>)

In [60]:
tf.matmul(a,z)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 246, 1009],
       [ 336, 1357],
       [ 426, 1705]], dtype=int32)>

In [61]:
#transpose
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [63]:
tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [66]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[102, 111, 120],
       [132, 144, 156]], dtype=int32)>

### Dot product

In [69]:
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[102, 111, 120],
       [132, 144, 156]], dtype=int32)>

In [75]:
tf.matmul(tf.reshape(x, shape=(2,3)), y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186]], dtype=int32)>

In [76]:
y = tf.constant([[7,8], [9, 10], [11, 12]])

In [77]:
#print values
print("Normal y:", y)
print("y reshaped to (2,3):", tf.reshape(y, shape=(2,3)))
print("y transposed:", tf.transpose(y))

Normal y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
y reshaped to (2,3): tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
y transposed: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
