<a href="https://colab.research.google.com/github/sameer203/Tensorflow_/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor introduction

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [5]:
# Create tensors with tf.constants()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [7]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [12]:
#create a matrix
matrix = tf.constant([[10, 7],
                     [7,10]])

In [13]:
matrix.ndim

2

In [16]:
matrix_1 = tf.constant([[10., 7.],
                        [3.,2.],
                        [8.,10.]], dtype=tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8., 10.]], dtype=float16)>

In [15]:
matrix_1.ndim

2

In [17]:
#Create a tensor
tensor = tf.constant([[[1,2, 3,],
                       [4,5,6,]],
                       [[7,8, 9,],
                      [10, 11, 12]],
                      [[13, 14,15],
                      [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [18]:
tensor.ndim

3